# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0004_auto_20171005_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='rain_value',
            field=models.CharField(default=32, max_length=250),
            preserve_default=False,
        ),
    ]
