# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0005_temperature_rain_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
            ],
        ),
    ]
