# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0006_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='plant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temperature.Plants'),
        ),
    ]
